const ASSETS = [
    // Charakter
    'img/charakter/walk/walk1.png',
    'img/charakter/walk/walk2.png',
    'img/charakter/walk/walk3.png',
    'img/charakter/walk/walk4.png',
    'img/charakter/walk/walk5.png',
    'img/charakter/walk/walk6.png',
    'img/charakter/jump/jump1.png',
    'img/charakter/jump/jump2.png',
    'img/charakter/jump/jump3.png',
    'img/charakter/jump/jump4.png',
    'img/charakter/jump/jump5.png',
    'img/charakter/jump/jump6.png',
    'img/charakter/dead/death1.png',
    'img/charakter/dead/death2.png',
    'img/charakter/dead/death3.png',
    'img/charakter/dead/death4.png',
    'img/charakter/dead/death5.png',
    'img/charakter/dead/death6.png',
    'img/charakter/dead/death7.png',
    'img/charakter/dead/death8.png',
    'img/charakter/dead/death9.png',
    'img/charakter/dead/death10.png',
    'img/charakter/hurt/hurt1.png',
    'img/charakter/hurt/hurt2.png',
    'img/charakter/hurt/hurt3.png',
    'img/charakter/hurt/hurt4.png',
    'img/charakter/attack/attack1.png',
    'img/charakter/attack/attack2.png',
    'img/charakter/attack/attack3.png',
    'img/charakter/attack/attack4.png',
    'img/charakter/attack/attack5.png',
    'img/charakter/attack/attack6.png',
    'img/charakter/attack/attack7.png',

    // Goblin
    'img/goblin/walk1.png',
    'img/goblin/walk2.png',
    'img/goblin/walk3.png',
    'img/goblin/walk4.png',
    'img/goblin/walk5.png',
    'img/goblin/walk6.png',
    'img/goblin/hurt/hurt1.png',
    'img/goblin/hurt/hurt2.png',
    'img/goblin/hurt/hurt3.png',
    'img/goblin/death/death1.png',
    'img/goblin/death/death2.png',
    'img/goblin/death/death3.png',
    'img/goblin/death/death4.png',

    // Endboss
    'img/endboss/walk/Walk1.png',
    'img/endboss/walk/Walk2.png',
    'img/endboss/walk/Walk3.png',
    'img/endboss/walk/Walk4.png',
    'img/endboss/walk/Walk5.png',
    'img/endboss/walk/Walk6.png',
    'img/endboss/hurt/Hurt1.png',
    'img/endboss/hurt/Hurt2.png',
    'img/endboss/dead/Death0.png',
    'img/endboss/dead/Death1.png',
    'img/endboss/dead/Death2.png',
    'img/endboss/dead/Death3.png',
    'img/endboss/dead/Death4.png',
];
